export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const ASSISTANT_SEARCH_TEST_FOR_SPEAK = 'ASSISTANT_SEARCH_TEST_FOR_SPEAK';

export const WINDOW_RESIZE_COUNT = 'WINDOW_RESIZE_COUNT';
export const WAKEUP_ASSISTANT = 'WAKEUP_ASSISTANT';

export const ALL_SUBJECT_STUDENT_SCHOOL_REQUEST = 'ALL_SUBJECT_STUDENT_SCHOOL_REQUEST';
export const ALL_SUBJECT_STUDENT_SCHOOL_SUCCESS = 'ALL_SUBJECT_STUDENT_SCHOOL_SUCCESS';


export const ALL_CLASS_STANDARD_GRADES_DATA_REQUEST = 'ALL_CLASS_STANDARD_GRADES_DATA_REQUEST';
export const ALL_CLASS_STANDARD_GRADES_DATA_SUCCESS = 'ALL_CLASS_STANDARD_GRADES_DATA_SUCCESS';

export const SUBJECT_ALL_CHAPTER_DATA_REQUEST = 'SUBJECT_ALL_CHAPTER_DATA_REQUEST';
export const SUBJECT_ALL_CHAPTER_DATA_SUCCESS = 'SUBJECT_ALL_CHAPTER_DATA_SUCCESS';

export const SELECTED_SUBJECT_DATA_REQUEST = 'SELECTED_SUBJECT_DATA_REQUEST';
export const SELECTED_SUBJECT_DATA_SUCCESS = 'SELECTED_SUBJECT_DATA_SUCCESS';

export const SELECTED_CHAPTER_DATA_REQUEST = 'SELECTED_CHAPTER_DATA_REQUEST';
export const SELECTED_CHAPTER_DATA_SUCCESS = 'SELECTED_CHAPTER_DATA_SUCCESS';


export const CHAPTER_ALL_TOPICS_DATA_REQUEST = 'CHAPTER_ALL_TOPICS_DATA_REQUEST';
export const CHAPTER_ALL_TOPICS_DATA_SUCCESS = 'CHAPTER_ALL_TOPICS_DATA_SUCCESS';

export const CHAPTER_ALL_TEST_DATA_REQUEST = 'CHAPTER_ALL_TEST_DATA_REQUEST';
export const CHAPTER_ALL_TEST_DATA_SUCCESS = 'CHAPTER_ALL_TEST_DATA_SUCCESS';

export const TEST_ALL_QUESTION_OPTIONS_DATA_REQUEST = 'TEST_ALL_QUESTION_OPTIONS_DATA_REQUEST';
export const TEST_ALL_QUESTION_OPTIONS_DATA_SUCCESS = 'TEST_ALL_QUESTION_OPTIONS_DATA_SUCCESS';

export const TEST_DATA_BY_TEST_ID_REQUEST = 'TEST_DATA_BY_TEST_ID_REQUEST';
export const TEST_DATA_BY_TEST_ID_SUCCESS = 'TEST_DATA_BY_TEST_ID_SUCCESS';

export const CHAPTER_TOPICS_DATA_BY_TOPIC_ID_SUCCESS = 'CHAPTER_TOPICS_DATA_BY_TOPIC_ID_SUCCESS';
export const VIDEO_PROGRESS_UPDATED = 'VIDEO_PROGRESS_UPDATED';

export const USER_HISTORY_CHAPTER_SUBJECT_TOPIC_DATA_REQUEST = 'USER_HISTORY_CHAPTER_SUBJECT_TOPIC_DATA_REQUEST';
export const USER_HISTORY_CHAPTER_SUBJECT_TOPIC_DATA_SUCCESS = 'USER_HISTORY_CHAPTER_SUBJECT_TOPIC_DATA_SUCCESS';

export const ALL_SCHOOL_DATA_LIST_REQUEST = 'ALL_SCHOOL_DATA_LIST_REQUEST';
export const ALL_SCHOOL_DATA_LIST_SUCCESS = 'ALL_SCHOOL_DATA_LIST_SUCCESS';

export const ALL_SUBJECT_DATA_LIST_REQUEST = 'ALL_SUBJECT_DATA_LIST_REQUEST';
export const ALL_SUBJECT_DATA_LIST_SUCCESS = 'ALL_SUBJECT_DATA_LIST_SUCCESS';

export const ALL_CHAPTER_DATA_LIST_REQUEST = 'ALL_CHAPTER_DATA_LIST_REQUEST';
export const ALL_CHAPTER_DATA_LIST_SUCCESS = 'ALL_CHAPTER_DATA_LIST_SUCCESS';

export const ALL_TOPIC_DATA_LIST_REQUEST = 'ALL_TOPIC_DATA_LIST_REQUEST';
export const ALL_TOPIC_DATA_LIST_SUCCESS = 'ALL_TOPIC_DATA_LIST_SUCCESS';

export const USER_CLASS_SUBJECT_DATA_REQUEST = 'USER_CLASS_SUBJECT_DATA_REQUEST';
export const USER_CLASS_SUBJECT_DATA_SUCCESS = 'USER_CLASS_SUBJECT_DATA_SUCCESS';

export const CHAT_DATA_JS_PROGRESS_DATA_SET_REQUEST = 'CHAT_DATA_JS_PROGRESS_DATA_SET_REQUEST';
export const CHAT_DATA_JS_PROGRESS_DATA_SET_SUCCESS = 'CHAT_DATA_JS_PROGRESS_DATA_SET_SUCCESS';

export const CHAPTER_ALL_TOPICS_SEARCH_DATA_REQUEST = 'CHAPTER_ALL_TOPICS_SEARCH_DATA_REQUEST';
export const CHAPTER_ALL_TOPICS_SEARCH_DATA_SUCCESS = 'CHAPTER_ALL_TOPICS_SEARCH_DATA_SUCCESS';

export const ALL_SYLLABUS_DATA = 'ALL_SYLLABUS_DATA';
export const ALL_CLASS_SECTION_DATA = 'ALL_CLASS_SECTION_DATA';
export const ALL_CLASS_STANDARD_DATA = 'ALL_CLASS_STANDARD_DATA';

export const USER_PROFILE_IN_EDIT_MODE = 'USER_PROFILE_IN_EDIT_MODE';
export const USER_VOICE_ASSISTANT_SELECTION = 'USER_VOICE_ASSISTANT_SELECTION';

export const TEACHER_ALL_CLASSES_DATA_REQUEST = 'TEACHER_ALL_CLASSES_DATA_REQUEST';
export const TEACHER_ALL_CLASSES_DATA_SUCCESS = 'TEACHER_ALL_CLASSES_DATA_SUCCESS';
